ALTER TABLE home_features ADD COLUMN feature1_icon VARCHAR(255) DEFAULT NULL;
ALTER TABLE home_features ADD COLUMN feature2_icon VARCHAR(255) DEFAULT NULL;
ALTER TABLE home_features ADD COLUMN feature3_icon VARCHAR(255) DEFAULT NULL;
ALTER TABLE home_features ADD COLUMN feature4_icon VARCHAR(255) DEFAULT NULL;
